services:
  nest-app:
    image: registry.cn-hangzhou.aliyuncs.com/lulab_docker/lulab_backend:dev1.0.0
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - lulab_network
  redis:
    image: redis:8.2.1-alpine
    restart: always
    # ⚠️ 如果无需对外暴露，建议去掉下面一行，改用不暴露端口：
    ports:
      - '${REDIS_PORT:-6379}:6379'
    # 若只允许本机访问，可以这样：
    # ports:
    #   - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command:
      [
      "redis-server",
      "--appendonly","yes",
      "--requirepass","${REDIS_PASSWORD}",
      "--databases","${REDIS_DATABASES:-16}",
      "--maxmemory","${REDIS_MAXMEMORY:-256mb}",
      "--maxmemory-policy","allkeys-lru"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - lulab_network

volumes:
  redis_data:

networks:
  lulab_network:
    driver: bridge
    name: lulab_backend_network